FROM python:3.9

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY *.py /app
COPY launchWeb.sh /app
RUN chmod +x /app/launchWeb.sh
COPY dev-key.pem /app
COPY dev-cert.pem /app

ENV PORT=80
ENV SECURE=no
ENV TCPPORTS=none

# CMD ["sh", "-c", "fastapi run app/main.py --port ${PORT}"]
CMD ["sh", "-c", "./launchWeb.sh"]

# If running behind a proxy like Nginx or Traefik add --proxy-headers
# CMD ["fastapi", "run", "app/main.py", "--port", "80", "--proxy-headers"]