FROM python:3.9

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY *.py /app

ENV TCPPORTS=3197,3199

CMD ["sh", "-c", "python mainTcp.py"]
